// <auto-generated />
using GerenciamentoDeOportunidades.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoDeOportunidades.Migrations
{
    [DbContext(typeof(OportunidadesContext))]
    [Migration("20220903190653_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GerenciamentoDeOportunidades.Oportunidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodEstadoIBGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescricaoDeAtividades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("ValorMonetario")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioEmailId");

                    b.ToTable("Oportunidades");
                });

            modelBuilder.Entity("GerenciamentoDeOportunidades.Usuario", b =>
                {
                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Regiao")
                        .HasColumnType("int");

                    b.HasKey("EmailId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("GerenciamentoDeOportunidades.Oportunidade", b =>
                {
                    b.HasOne("GerenciamentoDeOportunidades.Usuario", null)
                        .WithMany("Oportunidades")
                        .HasForeignKey("UsuarioEmailId");
                });

            modelBuilder.Entity("GerenciamentoDeOportunidades.Usuario", b =>
                {
                    b.Navigation("Oportunidades");
                });
#pragma warning restore 612, 618
        }
    }
}
